# run to install: conda env create --file environment.yml
# run to update: conda env update --name myenv --file environment.yml --prune
# run using mamba to install: mamba env create -f environment.yml
name: py_ml_packaging_classification

channels:
- conda-forge
- pytorch

dependencies:
# conda installation
- python>=3.11
- ipython_genutils
- ipykernel
- ipywidgets
- jupyterlab
- pip
- mamba
- pyyaml
- numpy>=1.22
- matplotlib
- pandas>=2.0
- pandas-datareader
- scikit-learn>=1.1
- scipy
- seaborn
- bokeh
- lightgbm
- pytorch
- lightning
- optuna
- imbalanced-learn
- mlflow
- pycaret>=3.0
- autogluon
- pytest
- pip:
  # pip installation
  # - optuna.integration
  - black
  - 'black[jupyter]'
  - isort
  - optuna.integration
