name: py_ml_packaging_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - pip=23.3.2
  - ipython_genutils=0.2.0
  - ipykernel=6.28.0
  - jupyterlab=4.0.10
  - matplotlib=3.8.2
  - seaborn=0.13.1
  - bokeh=3.3.3
  - numpy=1.26.3
  - pandas=2.1.4
  - pandas-datareader=0.10.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - lightgbm=4.1.0
  - pytorch=2.0.0
  - pytorch-lightning=2.0.9
  - lightning=2.0.9.post0
  - optuna=3.5.0
  - imbalanced-learn=0.11.0
  - mlflow=2.9.2
  - autogluon=1.0.0
