version: "3.8" # Specifies which version of the Docker Compose file format to use
  
services: # Top level element to configure the arguments of multiple services
  myproject: # "project" refers to the name of your project/application for which configurations are defined. Multiple projects can be configured.
    build: # Tells Docker Compose to build the Docker image using the Dockerfile in the specified directory.
      context: .
      dockerfile: ./Dockerfile.debug
    image: dat/dev-container-datascience # Explicit way to define the image name
    # networks:
    #   - app-net

    volumes: # Volumes are persistent data stores (outside container), mounted to be usable by the container
      - ../:/workspace

    working_dir: /workspace

    
    command:
      - sh -c "chmod -R 777 /workspace && tail -f /dev/null" # Set permissions on the working directory for root user